### ISSUE TITLE
cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by paulaburke** [paulaburke/rubiksq#1]
The below code is giving me trouble. This is lines 23-31 in main.jss. When I click on the button with the appropriate class, I get the console error "cannot read property 'value' of undefined." However, when I used 'this.value' in the if statement, it worked fine. And if I use the console, I can set i and use play[i].value to change the selected item's value. My guess is that the if statement isn't retaining a value for i, but when I added another variable inside the function, it still didn't work. I know I could just use this.value to update the value of the selected button, but I need to also update adjacent buttons, and I wanted to be able to say play[i+1].value++ in the same function.
```
for (var i = 0; i < play.length; i++) {
    play[i].addEventListener("click", function(){
    if (play[i].value === "3") {
      play[i].value = 0;
    } else {
      play[i].value++;
    }
  });
  }
```

**Comment by paulaburke** [comment]
I learned about closures so I fixed it.

**Comment by h4w5** [comment]
Good job! Thanks for closing!
